site_name: obsidian-mkdocs template

theme:
    name: 'material'
    language: pt-BR
    logo: Logo.png
    favicon: favicon.ico
    features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - search.suggest
    palette:
      scheme: slate
      primary: teal
      accent: cyan
    font:
      text: Poppins
      

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - attr_list
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - offline

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

copyright: ⌘ By Moykhaile